"""Change data type of price column

Revision ID: 816fe0a70a24
Revises: dc7e9ba62155
Create Date: 2023-09-20 16:28:55.672061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816fe0a70a24'
down_revision = 'dc7e9ba62155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
